### ISSUE TITLE
Error while running walkmod-pmd transformations

### ISSUE THREAD

**Issue by pkmusthafa** [walkmod/walkmod-pmd-plugin#28]
Please help, I am getting the below error while running pmd transformations.

 ```
INFO [main] - ** STARTING TRANSFORMATIONS CHAINS **
--------------------------------------------------------------------------------
 INFO [main] - TRANSFORMATION CHAIN FAILS

--------------------------------------------------------------------------------
 INFO [main] - Total time: 0.013 seconds
 INFO [main] - Finished at: Mon, 22 Jan 2018 18:13:51
 INFO [main] - Final memory: 87 M/ 119 M
--------------------------------------------------------------------------------
 INFO [main] - Please, see the walkmod log file for details
ERROR [main] - TRANSFORMATION CHAIN (default) FAILS
Sorry, it is impossible to load the bean pmd:BooleanInstantiation. Please, assure that it is a valid class name and the library which contains it is in the classpath - org.walkmod.util.location.LocationImpl@66b5d124
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
        at org.walkmod.conf.entities.impl.ConfigurationImpl.getBean(ConfigurationImpl.java:286)
        at org.walkmod.impl.DefaultChainWalkerAdapter.prepare(DefaultChainWalkerAdapter.java:107)
        at org.walkmod.impl.DefaultChainAdapter.prepare(DefaultChainAdapter.java:160)
        at org.walkmod.impl.DefaultChainAdapterFactory.createChainProxy(DefaultChainAdapterFactory.java:49)
        at org.walkmod.conf.entities.impl.ConfigurationImpl.executeAllChains(ConfigurationImpl.java:605)
        at org.walkmod.conf.entities.impl.ConfigurationImpl.execute(ConfigurationImpl.java:822)
        at org.walkmod.WalkModFacade.run(WalkModFacade.java:284)
        at org.walkmod.WalkModFacade.apply(WalkModFacade.java:142)
        at org.walkmod.commands.ApplyCommand.execute(ApplyCommand.java:40)
        at org.walkmod.WalkModDispatcher.execute(WalkModDispatcher.java:172)
        at org.walkmod.WalkModDispatcher.main(WalkModDispatcher.java:197)
Caused by: java.lang.ClassNotFoundException: pmd:BooleanInstantiation
        ... 17 more

```
please find the walkmod.xml file 

https://gist.github.com/anonymous/f0753a77d22a962332f7dd71a1308a62

Regards,

**Comment by rpau** [comment]
There is only one visible transformation for PMD:

https://github.com/walkmod/walkmod-pmd-plugin/blob/master/src/main/resources/META-INF/walkmod/walkmod-pmd-plugin.xml

The reason was to simplify the user experience providing the existing [PMD configuration file](http://pmd.sourceforge.net/pmd-4.3.0/howtomakearuleset.html) that they use to run PMD. To configure your walkmod xml, you need to add it as follows:

````
<transformation type="pmd:pmd">
    <param name="configurationFile">PATH_TO_YOUR_PMD_FILE.xml</param>
  </transformation>
````

**Comment by rpau** [comment]
I am closing the issue. If there is anything else to address, feel free to reopen it.
